CONTIKI_PROJECT = udp-client udp-server
all: $(CONTIKI_PROJECT)

CONTIKI=../..
MODULES += os/services/rpl-border-router
MODULES += os/services/shell
MODULES += os/services/simple-energest
include $(CONTIKI)/Makefile.include

